server {
    listen 80;
    # После покупки домена: замените _ на ваш домен, например youtubeclub.ru
    server_name _;

    root /var/www/youtube-club;
    index index.html;

    # Кэширование статики
    location ~* \.(css|js|ttf|gif|jpg|png|svg|ico)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }

    location / {
        try_files $uri $uri/ =404;
    }

    # Отключаем логирование фавикона
    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }
}
